config/routes.rb
Mmagap::Application.routes.draw do
  
  
  root :to => 'videos#index'
  
  
  #devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) 
  devise_for :admin_users, ActiveAdmin::Devise.config


  resources :student_teacher_profiles
  resources :comments
  resources :comment_likes
  resources :likes


  #resources :videos  
  
  
  #following system
  resources :relationships, only: [:create, :destroy]
 
  post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"
  get 'tags/:tag', to: 'videos#tag_page', as: :tag
  
 
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  devise_for :users, :controllers => {:registrations => "registrations"}
    
  #devise_for :users
  match 'users/:id' => 'users#show'

  devise_scope :user do
    get 'register' , :to => 'devise/registrations#new', as: :register
    get 'mydashboard', :to => 'users#dashboard', as: :mydashboard
    get 'user/following/:id', to: 'users#following', as: :following
    get 'user/followers/:id', to: 'users#followers', as: :followers
  end
  

  match '/home' => 'videos#index', :as => 'home'

  
  resources :videos do
    collection do
      #get 'lesson' => 'videos#lesson', :as => 'lesson'
      #post 'lesson_create' => 'videos#lesson_create', :as => 'lesson_create'
      get '/lesson' => 'videos#lesson', :as => 'lesson'
      post '/lesson' => 'videos#lesson_create', :as => 'lesson_create'
    end
  end
  
  get '/lesson' => 'videos#lesson', :as => 'lesson'
  post '/lesson' => 'videos#lesson_create', :as => 'lesson_create'
  
  get '/show_lesson_video/:id' => 'videos#show_lesson_video', :as => 'show_lesson_video'
  get '/purches_lesson_video/:id' => 'videos#purches_lesson_video', :as => 'purches_lesson_video'
  
  #get '/lesson_checkouts' => 'lesson_checkouts#index'
  
  resources :lesson_checkouts
  #get '/lesson_checkout/new/:video_id' => 'lesson_checkouts#new', :as => 'lesson_pay_new'
  #post '/lesson_checkout/new/:video_id' => 'lesson_checkouts#create', :as => 'lesson_pay_create'
  
  get '/lesson_checkout/new/' => 'lesson_checkouts#new', :as => 'lesson_pay_new'
  post '/lesson_checkout/new/' => 'lesson_checkouts#create', :as => 'lesson_pay_create'
  
  get '/paypal_pro/:id' => 'lesson_checkouts#paypal_pro', :as => 'paypal_pro'
  post '/paypal_pro/:id' => 'lesson_checkouts#paypal_do_direct', :as => 'paypal_do_direct'
  
  
  get '/paypal_success/:id' => 'lesson_checkouts#paypal_success', :as => 'paypal_success'
  get '/paypal_failure/:id' => 'lesson_checkouts#paypal_failure', :as => 'paypal_failure'
  get '/paypal_ipn/:id' => 'lesson_checkouts#paypal_ipn', :as => 'paypal_ipn'
  
  #get '/paypal_do_direct/:id' => 'lesson_checkouts#paypal_do_direct', :as => 'paypal_do_direct'
  #get '/paypal_do_direct/:id' => 'lesson_checkouts#paypal_do_direct_new', :as => 'paypal_do_direct_new'
 
  
  
  
  match '/tags' => 'videos#tag_page', :as => 'tags'
  resources :videos do
    member do
      get 'inappropriate'
    end 
          resources :comments
          member { post :vote }
    end


  resources :users
  resources :plans
  resources :subscriptions
  
  resources :inquiries, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end

  #get "paypal/new/:plan_id", to: "subscriptions#new", as: :new
  #get "paypal/checkout", to: "subscriptions#paypal_checkout", as: :paypal_checkout
  
  match '/paypal/checkout'=>'subscriptions#paypal_checkout'
  get '/paypal/checkout'=>'subscriptions#paypal_checkout'
  
  #get "paypal/checkout", to: "subscriptions#paypal_checkout"
 
 

  resources :requests
  resources :homes

  match "/404", :to => "videos#index"

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  match '/new_within_follow' => 'conversations#new_within_follow', via: :get
  match '/start' => 'conversations#start', :via => :get
  match '/find_user' => 'users#find_user', :via => :get

  resources :messages
    match '/profile' => 'users#profile', :via => :get
    match '/userspage' => 'static#userspage', :via => :get
    match '/help' => 'static#help', :via => :get
    match '/termsofuse' => 'static#termsofuse', :via => :get
    match '/aboutus' => 'static#aboutus', :via => :get
    match '/contactus' => 'static#contactus', :via => :get
  
  match 'cms_pages/show/:id' => 'cms_pages#show'
  
  
    
end

app/models/lesson_checkout.rb
require 'credit_card_validations/string'
class LessonCheckout < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :video
  
  attr_accessible :id, :video_id, :user_id, :payment_status, :created_at, :updated_at
  #attr_accessible :user_id, :video_id, :payment_status, :created_at, :updated_at, :email, :credit_card_number, :card_code, :credit_card_expires_on
  
  #attr_accessor :user_id, :video_id, :payment_status, :created_at, :updated_at
  
  attr_accessible :email
  attr_accessor :email
  
  validates_presence_of :email, presence: true
  validates_format_of :email, :with => /[-!#$&'*+\/=?`{|}~.\w]+@[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])*(\.[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])*)+$/,
                    :message => ' appears to be invalid'
  
     
  #validates_presence_of :credit_card_number, presence: true
  #validates_presence_of :card_number, presence: true
  #validates :visa, :mc, :discover, :amex, :presence => true, :if => :credit_card?
  
  #validates_presence_of :card_code, presence: true
  #validates_presence_of :card_month, presence: true
  #validates_presence_of :card_year, presence: true
  
  #validates :card_number, presence: true, credit_card_number: {brands: [:amex, :unionpay, :dankrot, :diners, :diners_us, :discover, :jcb, :laser, :maestro, :mastercard, :solo, :visa]}

end

app/controllers/lesson_checkouts_controller.rb
class LessonCheckoutsController < ApplicationController
  # GET /lesson_checkouts
  # GET /lesson_checkouts.json
  def index
    @lesson_checkouts = LessonCheckout.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lesson_checkouts }
    end
  end

  # GET /lesson_checkouts/1
  # GET /lesson_checkouts/1.json
  def show
    @lesson_checkout = LessonCheckout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson_checkout }
    end
  end

  # GET /lesson_checkouts/new
  # GET /lesson_checkouts/new.json
  def new
    
    #@lesson_checkout = params
    #@vid = params[:video_id]
    #@uid = current_user.id
    #
    #@lesson_checkout = LessonCheckout.new
    
    #@a = LessonCheckout.where("video_id = ? AND user_id = ?", @vid, @uid)
    #if  @a.nil?
    #  @lesson_checkout1['order_id'] = @a[:LessonCheckout]['id']
    #else
    #  
    #   #@lesson_checkout1 = LessonCheckout.create(LessonCheckout.new('lesson_checkout'=>:video_id=>@vid,:user_id=>@uid,:payment_status=>'pending', :created_at=>Time.now, :updated_at=>Time.now))
    #   #@lesson_checkout1.save
    #  
    #    #@lastinsertid =LessonCheckout.create(:user_id=> @uid,:video_id=> @vid, :payment_status=>'pending')
    #    #@lesson_checkout2['order_id'] = @lastinsertid.id
    #end  
    
    #@lesson_pay = Video.find(params[:video_id])
    #respond_to do |format|
    #  format.html # new.html.erb
    #  format.json { render json: @lesson_checkout }
    #  
    #end
  end

  # GET /lesson_checkouts/1/edit
  def edit
    @lesson_checkout = LessonCheckout.find(params[:id])
  end

  # POST /lesson_checkouts
  # POST /lesson_checkouts.json
  def create
    
    @vid = params[:lesson_checkout][:video_id]
    @uid = current_user.id
    @dd= Time.now
    params[:lesson_checkout]['user_id'] =  current_user.id
    params[:lesson_checkout]['payment_status'] = 'pending'
    params[:lesson_checkout]['created_at'] = Time.now
    params[:lesson_checkout]['updated_at'] = Time.now
    
    
    
    @a = LessonCheckout.where("user_id = ? AND video_id = ?", @uid, @vid).last
    
    if !@a.nil?
      @orderid = @a['id']
    else
      
      #@lesson_checkout = LessonCheckout.new(params[:LessonCheckout])
      #@lesson_checkout.save
      #@orderid = @lesson_checkout.id;
      
      @la = LessonCheckout.connection.insert("INSERT INTO lesson_checkouts (user_id,video_id, payment_status,created_at, updated_at) VALUES (#{@vid},#{@uid},'pending','#{@dd}','#{@dd}')")
      
      @orderid = @la
    end 
    
     redirect_to paypal_pro_path(@orderid)
    
    
    
    #@lesson_checkout.save
    #respond_to do |format|
    #  if @lesson_checkout.save
    #    format.html { redirect_to @lesson_checkout, notice: 'Lesson checkout was successfully created.' }
    #    format.json { render json: @lesson_checkout, status: :created, location: @lesson_checkout }
    #  else
    #    format.html { render action: "new" }
    #    format.json { render json: @lesson_checkout.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PUT /lesson_checkouts/1
  # PUT /lesson_checkouts/1.json
  def update
    @lesson_checkout = LessonCheckout.find(params[:id])

    respond_to do |format|
      if @lesson_checkout.update_attributes(params[:lesson_checkout])
        format.html { redirect_to @lesson_checkout, notice: 'Lesson checkout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson_checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lesson_checkouts/1
  # DELETE /lesson_checkouts/1.json
  def destroy
    @lesson_checkout = LessonCheckout.find(params[:id])
    @lesson_checkout.destroy

    respond_to do |format|
      format.html { redirect_to lesson_checkouts_url }
      format.json { head :no_content }
    end
  end
  
  
  
  
  def paypal_pro
    
    @OID = params['id'] 
    @order_status = LessonCheckout.where("id = ? ", @OID)
    
    @order_status.each do |v|
      @vid = v[:video_id]
      @lesson_pay = Video.find(@vid)
      @lesson_pay['order_id'] = @OID 
    end 
   
     
  end
  
  def paypal_do_direct
    
    @amount = params[:price] # amount paid
    @first_name = params[:firstname]
    @last_name = params[:lastname]
    @email = params[:email]
    @card_code = params[:card_code]
    @card_no = params[:credit_card_number] # credit card number
    @card_type = params[:card_type]['get_card'] # can be Visa, Mastercard, Amex etc
    @month = params[:credit_card_expires_on]['credit_card_ex(2i)']
    @year = params[:credit_card_expires_on]['credit_card_ex(1i)']
    @exp_date = @month+@year # expiry date of the credit card

    username = @API_USERNAME
    password = @API_PASSWORD
    signature = @API_SINGNATURE
    
    
    
    #ipaddress = '192.168.1.1' # can be any IP address
    #amount = '100.00' # amount paid
    #card_type = 'VISA' # can be Visa, Mastercard, Amex etc
    #card_no = '4512345678901234' # credit card number
    #exp_date = '022010' # expiry date of the credit card
    #first_name = 'Sau Sheong'
    #last_name = 'Chang'
    
    ipaddress = '192.168.1.1' # can be any IP address
    amount = @amount # amount paid
    card_type = @card_type # can be Visa, Mastercard, Amex etc
    card_no = @card_no # credit card number
    exp_date = @exp_date # expiry date of the credit card
    first_name = @first_name
    last_name = @last_name
        
    #paypal = Paypal.new(username, password, signature)
    #@response = paypal.do_direct_payment_sale(ipaddress, amount, card_type,card_no, exp_date, first_name, last_name)
    #
    #if @response.ack == 'Success' then
    #  # do your thing
    #  @OID = params['id']
    #  @order_status = LessonCheckout.find_by_id(@OID)
    #  @order_status.payment_status = 'success'
    #  @order_status.save
    #  
    #  @res = "Your payment process successfully completed."
    #else
    #  @res = "Your payment process have been failed"
    #end
  end
  
  
  
  def paypal_success
    
    @OID = params['id']
    
    if !@OID.nil?
      #@order_status = LessonCheckout.where("id = ? ", @OID)
      @order_status = LessonCheckout.find_by_id(@OID)
      @order_status.payment_status = 'success'
      @order_status.save
    end
  end
  
  def paypal_failure
    
    @OID = params['id']
    if !@OID.nil?
      #@order_status = LessonCheckout.where("id = ? ", @OID)
      @order_status = LessonCheckout.find_by_id(@OID)
      @order_status.payment_status = 'failed'
      @order_status.save
    end
  end
  
  def paypal_ipn
    
  end
end

app/helpers/lesson_checkouts_helper.rb
module LessonCheckoutsHelper
end

app/views/lesson_checkouts/_form.html (copy).erb
<%= form_for lesson_pay_new_path(params[:video_id]) do |f| %>

  
  <div class="form-inputs">
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
      <!--<input id="email" name="email" type="text" /><br />-->
      <%= show_field_error(@lesson_checkout, :email) %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lesson_checkouts/_form.html.erb
<div class="field">
  <%= radio_button_tag :pl_pay_with, :card, true %>
  <%= label_tag :pl_pay_with_card do %>
    <ul style="display: inline-block" id="pl_mycards">
       <li style="display: inline;width:50px;float: left"><%= image_tag "cards/visa.png", :width=>"30", :height=>"30" %></li>
       <li style="display: inline;width:50px;float: left"><%= image_tag "cards/mastercard.png", :width=>"30", :height=>"30" %></li>
       <li style="display: inline;width:50px;float: left"><%= image_tag "cards/discover.png", :width=>"30", :height=>"30" %></li>
       <li style="display: inline;width:50px;float: left"><%= image_tag "cards/american_express.png", :width=>"30", :height=>"30" %></li>
       <li style="display: inline;width:50px;float: left"><%= image_tag "cards/jcb.png", :width=>"30", :height=>"30" %></li>
   </ul>  
  <% end %>
  <%= radio_button_tag :pl_pay_with, :paypal %>
  <%= label_tag :lp_pay_with_paypal do %>
  <ul>
    <li><%= image_tag "cards/paypal.png", :width=>"30", :height=>"30" %></li>
  </ul>  
  <% end %>
</div>

<div id="pl_paypal_checkout" style="display:none">
   
    <form class="red" action="<%= @PAYPAL_URL %>" name="gateway_form" method="POST">

    
    
      <fieldset>
        <legend>Your Payment Gateway:</legend>
       <p></p><h1 style="color:#308702;text-align:center;">Paypal Payment Pro</h1><p></p>
      </fieldset>
      <fieldset>
       <legend>Your Payment Information:</legend>
            <input type="hidden" value="2" name="rm">
            <input type="hidden" value="_xclick" name="cmd">
            <input type="hidden" value="<%= @MERCHANT_id %>" name="business">
            <input type="hidden" value="USD" name="currency_code">
            <input type="hidden" value="<%= @hostname %>/paypal_success/<%= @lesson_pay.order_id %>" name="return">
            <input type="hidden" value="<%= @hostname %>/paypal_failure/<%= @lesson_pay.order_id %>" name="cancel_return">
            <input type="hidden" value="h<%= @hostname %>/paypal_ipn/<%= @lesson_pay.order_id %>" name="notify_url">
            <input type="hidden" value="<%= current_user.username %>" name="first_name">
            <input type="hidden" value="<%= current_user.username %>" name="last_name">
            <input type="hidden" value="<%= current_user.email %>" name="email">
            <input type="hidden" value="<%= current_user.address %>" name="address">
            <input type="hidden" value="New York" name="city">
            <input type="hidden" value="10001" name="zip">
            <input type="hidden" value="NY" name="state">
            <input type="hidden" value="US" name="country">
            <input type="hidden" value="<%= @lesson_pay.title %>" name="item_name">
            <input type="hidden" value="<%= @lesson_pay.price %>" name="amount">
            <input type="hidden" value="1" name="quintity ">
            <input type="hidden" value="<%= @lesson_pay.description %>" name="descriptin">
            <input type="hidden" value="001" name="item_number">  
              
             <label style="width:95%;" class="float" for="input-one">
                   <span style="padding-left:5px;"><strong>first name: </strong></span>
                   <span style="margin-left:100px; align:left;float:right;"><%= current_user.username %></span></label>
             
             <label style="width:95%;" class="float" for="input-one">
                   <span style="padding-left:5px;"><strong>last name: </strong></span>
                   <span style="margin-left:100px;align:left;float:right;"><%= current_user.username %></span></label>
             
             <label style="width:95%;" class="float" for="input-one">
                   <span style="padding-left:5px;"><strong>email: </strong></span>
                   <span style="margin-left:100px;align:left;float:right;"><%= current_user.email %>
             </label>
             
             <label style="width:95%;" class="float" for="input-one">
                   <span style="padding-left:5px;"><strong>address: </strong></span>
                   <span style="margin-left:100px;align:left;float:right;"><%= current_user.address %></span>
             </label>
             
             <label style="width:95%;" class="float" for="input-one">
                   <span style="padding-left:5px;"><strong>city: </strong></span>
                   <span style="margin-left:100px;align:left;float:right;">New York
             </label>
             
             <label style="width:95%;" class="float" for="input-one">
                   <span style="padding-left:5px;"><strong>zip: </strong></span>
                   <span style="margin-left:100px;align:left;float:right;">10001</span>
             </label>
             
             <label style="width:95%;" class="float" for="input-one">
                   <span style="padding-left:5px;"><strong>state: </strong></span>
                   <span style="margin-left:100px;align:left;float:right;">NY</span>
             </label>
            
             <label style="width:95%;" class="float" for="input-one">
                   <span style="padding-left:5px;"><strong>country: </strong></span>
                   <span style="margin-left:100px;align:left;float:right;">sdfg</span>
             </label>
             
             <label style="width:95%;" class="float" for="input-one">
                   <span style="padding-left:5px;"><strong>item name: </strong></span>
                   <span style="margin-left:100px;align:left;float:right;"><%= @lesson_pay.title %></span>
             </label>
          
             <label style="width:95%;" class="float" for="input-one">
                   <span style="padding-left:5px;"><strong>amount: </strong></span>
                   <span style="margin-left:100px;align:left;float:right;"><%= @lesson_pay.price %></span>
             </label>
             
             <label style="width:95%;" class="float" for="input-one">
                   <span style="padding-left:5px;"><strong>descriptin: </strong></span>
                   <span style="margin-left:100px;align:left;float:right;"><%= @lesson_pay.description %></span>
             </label>
            
             <label style="width:95%;" class="float" for="input-one">
                   <span style="padding-left:5px;"><strong>item number: </strong></span>
                   <span style="margin-left:100px;align:left;float:right;">001</span>
             </label>
             <input type="hidden" value="Instant Support Plan" name="custom">
              
       </fieldset>
       <fieldset>
             <input type="button" onclick="history.go(-1);" class="submit-button" value="Back">
                   <input type="submit" value="Pay Now" class="submit-button">
                   <p></p>
       </fieldset>
    </form>    
     
</div>



<div id="pl_billing_fields">
  <%= form_for lesson_pay_create_path(params[:video_id]), :html =>{:id=>"formValidate"} do |f| %>

      <div class="field">
        
        First Name <br>
        <%= f.text_field :firstname, name: :firstname  %>
        <%#= show_field_error(@lesson_checkout, :firstname) %>
      </div>
      <div class="field">
        Last Name <br>
        <%= f.text_field :lastname, name: :lastname  %>
        <%#= show_field_error(@lesson_checkout, :lastname) %>
      </div>
      <div class="field">
        Amount<br>
                
       <%= f.text_field :price, name: :price, :readonly=>true,  :value=>@lesson_pay.price %>
        
        <%#= show_field_error(@lesson_checkout, :price) %>
      </div>
      
    
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email, name: :email  %>
        <%#= show_field_error(@lesson_checkout, :email) %>
      </div>
        <div class="field">
          <%= label_tag :card_type, "Credit Card type" %>
          <%= select("card_type", "get_card", [['VISA', 'visa'],['American Express', 'american_express'],['MasterCard', 'mastercard'],   ['JCB', 'jcb']]) %>
          <%#= show_field_error(@lesson_checkout, :card_number) %>
        </div>
        <div class="field">
          <%= label_tag :credit_card_number, "Credit Card Number" %>
          <%= text_field_tag :credit_card_number, nil, name: :credit_card_number %>
          <%#= show_field_error(@lesson_checkout, :credit_card_number) %>
        </div>
        
        
        
        <div class="field">
          <%= label_tag :card_code, "Security Code on Card (CVV)" %>
          <%= text_field_tag :card_code, nil, name: :card_code %>
          <%#= show_field_error(@lesson_checkout, :card_code) %>
        </div>
        <div class="field">
          <%= label_tag :card_month, "Card Expiration" %>
          <%#= f.date_select :credit_card_expires_on, order: [:month, :year] %>
          <%= date_select("credit_card_expires_on", "credit_card_ex", :order => [:month, :year])%>
          
          
          
          <%#= show_field_error(@lesson_checkout, :credit_card_expires_on) %>
        </div>
      
      <div id="stripe_error">
      <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
      </div>
      <div class="actions">
        <%= f.submit "Pay Now" %>
      </div>
    
   <% end %>
 </div>

</script>

app/views/lesson_checkouts/create.html.erb
<h1>Pyament</h1>


<%= debug @name %>

<%#= debug @a[:lesson_checkout].size %>
<%#= debug @aaa %>
<%#= debug @orderid %>

<%#= render 'form' %>

  
  

app/views/lesson_checkouts/edit.html.erb
<h1>Editing lesson_checkout</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson_checkout %> |
<%= link_to 'Back', lesson_checkouts_path %>

app/views/lesson_checkouts/index.html.erb
<h1>Listing lesson_checkouts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lesson_checkouts.each do |lesson_checkout| %>
  <tr>
    <td><%= link_to 'Show', lesson_checkout %></td>
    <td><%= link_to 'Edit', edit_lesson_checkout_path(lesson_checkout) %></td>
    <td><%= link_to 'Destroy', lesson_checkout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lesson checkout', new_lesson_checkout_path %>

app/views/lesson_checkouts/new.html.erb
<h1>New lesson_checkout</h1>
<%#= render 'form' %>


<%#= link_to 'Back', lesson_checkouts_path %>

app/views/lesson_checkouts/paypal_do_direct.html.erb
<%#= debug @result %>
<!--<%= @amount %><br>
<%= @first_name %><br>
<%= @last_name %><br>
<%= @email %><br>
<%= @card_code %><br>
<%= @card_no %><br>
<%= @card_type %><br>
<%= @month %><br>
<%= @year %><br>
<%= @exp_date %>-->


<h2 style="color: green"><%= @res %></h2>

app/views/lesson_checkouts/paypal_failure.html.erb
<h2 style="color: red">Paypal Failure.</h2>

app/views/lesson_checkouts/paypal_ipn.html.erb
<h2 style="color: yellow">Paypal ipn.</h2>

app/views/lesson_checkouts/paypal_pro.html.erb
<h1>Pyament</h1>


<%#= @hostname %>
<%#= @PAYPAL_URL %>

<%#=  debug @lesson_pay %>


<%= render 'form' %>

<%#= link_to 'Back', lesson_checkouts_path %>

app/views/lesson_checkouts/paypal_success.html.erb
<h2 style="color: green">Paypal Successful.</h2>

app/views/lesson_checkouts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_lesson_checkout_path(@lesson_checkout) %> |
<%= link_to 'Back', lesson_checkouts_path %>