config/routes.rb
Mmagap::Application.routes.draw do
  
  
  root :to => 'videos#index'
  
  
  #devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) 
  devise_for :admin_users, ActiveAdmin::Devise.config


  resources :student_teacher_profiles
  resources :comments
  resources :comment_likes
  resources :likes


  #resources :videos  
  
  
  #following system
  resources :relationships, only: [:create, :destroy]
 
  post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"
  get 'tags/:tag', to: 'videos#tag_page', as: :tag
  
 
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  devise_for :users, :controllers => {:registrations => "registrations"}
    
  #devise_for :users
  match 'users/:id' => 'users#show'

  devise_scope :user do
    get 'register' , :to => 'devise/registrations#new', as: :register
    get 'mydashboard', :to => 'users#dashboard', as: :mydashboard
    get 'user/following/:id', to: 'users#following', as: :following
    get 'user/followers/:id', to: 'users#followers', as: :followers
  end
  

  match '/home' => 'videos#index', :as => 'home'

  
  resources :videos do
    collection do
      #get 'lesson' => 'videos#lesson', :as => 'lesson'
      #post 'lesson_create' => 'videos#lesson_create', :as => 'lesson_create'
      get '/lesson' => 'videos#lesson', :as => 'lesson'
      post '/lesson' => 'videos#lesson_create', :as => 'lesson_create'
    end
  end
  
  get '/lesson' => 'videos#lesson', :as => 'lesson'
  post '/lesson' => 'videos#lesson_create', :as => 'lesson_create'
  
  get '/show_lesson_video/:id' => 'videos#show_lesson_video', :as => 'show_lesson_video'
  get '/purches_lesson_video/:id' => 'videos#purches_lesson_video', :as => 'purches_lesson_video'
  
  #get '/lesson_checkouts' => 'lesson_checkouts#index'
  
  resources :lesson_checkouts
  #get '/lesson_checkout/new/:video_id' => 'lesson_checkouts#new', :as => 'lesson_pay_new'
  #post '/lesson_checkout/new/:video_id' => 'lesson_checkouts#create', :as => 'lesson_pay_create'
  
  get '/lesson_checkout/new/' => 'lesson_checkouts#new', :as => 'lesson_pay_new'
  post '/lesson_checkout/new/' => 'lesson_checkouts#create', :as => 'lesson_pay_create'
  
  get '/paypal_pro/:id' => 'lesson_checkouts#paypal_pro', :as => 'paypal_pro'
  post '/paypal_pro/:id' => 'lesson_checkouts#paypal_do_direct', :as => 'paypal_do_direct'
  
  
  get '/paypal_success/:id' => 'lesson_checkouts#paypal_success', :as => 'paypal_success'
  get '/paypal_failure/:id' => 'lesson_checkouts#paypal_failure', :as => 'paypal_failure'
  get '/paypal_ipn/:id' => 'lesson_checkouts#paypal_ipn', :as => 'paypal_ipn'
  
  #get '/paypal_do_direct/:id' => 'lesson_checkouts#paypal_do_direct', :as => 'paypal_do_direct'
  #get '/paypal_do_direct/:id' => 'lesson_checkouts#paypal_do_direct_new', :as => 'paypal_do_direct_new'
 
  
  
  
  match '/tags' => 'videos#tag_page', :as => 'tags'
  resources :videos do
    member do
      get 'inappropriate'
    end 
          resources :comments
          member { post :vote }
    end


  resources :users
  resources :plans
  resources :subscriptions
  
  resources :inquiries, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end

  #get "paypal/new/:plan_id", to: "subscriptions#new", as: :new
  #get "paypal/checkout", to: "subscriptions#paypal_checkout", as: :paypal_checkout
  
  match '/paypal/checkout'=>'subscriptions#paypal_checkout'
  get '/paypal/checkout'=>'subscriptions#paypal_checkout'
  
  #get "paypal/checkout", to: "subscriptions#paypal_checkout"
 
 

  resources :requests
  resources :homes

  match "/404", :to => "videos#index"

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  match '/new_within_follow' => 'conversations#new_within_follow', via: :get
  match '/start' => 'conversations#start', :via => :get
  match '/find_user' => 'users#find_user', :via => :get

  resources :messages
    match '/profile' => 'users#profile', :via => :get
    match '/userspage' => 'static#userspage', :via => :get
    match '/help' => 'static#help', :via => :get
    match '/termsofuse' => 'static#termsofuse', :via => :get
    match '/aboutus' => 'static#aboutus', :via => :get
    match '/contactus' => 'static#contactus', :via => :get
  
  match 'cms_pages/show/:id' => 'cms_pages#show'
  
  
    
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :user_id, :parent_id, :commentable_type, :commentable_id  
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :comment_likes

  validates :content, :user_id, presence: true

  def was_not_liked_by? user
    !self.comment_likes.find_by_user_id(user.id)
  end

  def was_liked_positive_by? user_id
    user_like = self.comment_likes.find_by_user_id(user_id)
    user_like.like_or_not if user_like
  end
end 

app/controllers/comments_controller.rb
Module.instance_method(:initialize_copy).bind(CommentsController).call(Class.new(ApplicationController)) if defined? CommentsController
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @commentable = Video.find(params[:video_id])
    @comment = @commentable.comments.new
  end
  
  def create
    if params[:comment][:commentable_type] == 'Video'
      @commentable = Video.find(params[:comment][:commentable_id])
    elsif params[:comment][:commentable_type] == 'StudentTeacherProfile'
      @commentable = StudentTeacherProfile.find(params[:comment][:commentable_id])
    else
      @commentable = Comment.find(params[:comment][:commentable_id])
    end
    @comment = @commentable.comments.new(params[:comment])
    @comment.user_id= current_user.id 
		if @comment.save
      if params[:comment][:commentable_type] == 'StudentTeacherProfile'
        MessageSender.send_message(@comment.content, current_user, @commentable.user)
        redirect_to @commentable, notice: 'Message sended!'
      else
  		  redirect_to Video.find(params[:video_id]), notice: "Comment created."
      end
  	else
      if params[:comment][:commentable_type] == 'StudentTeacherProfile'
        redirect_to @commentable, notice: 'Try again!'
      else
    	 redirect_to Video.find(params[:video_id]), notice: 'Try again! '
      end
 		end
	end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<style>
#comUser a{
color:#FFF;
padding: 5px;

}
.delCom a{
color:#C00;

}
#comments{
	border:3px solid #eee; width:500px;margin-bottom:10px;
	
}
#comTitle{background:#999;}
#comUser{font-size:20px; color:#666;}
#comImg{border:1px solid #eee; width:50px;float:left;background:#ccc; padding:7px;}
</style>



<div id="comWrap">
  <h1>Comments</h1>
  <% @comments.order('id DESC').each_with_index do |comment,index| %>
    <%= render(:template =>"comments/comment", :layout => nil , :locals => { comment: comment, temp: 0 }) %>
    <% 
      temp = 0 
      content = ""
    %>
    <%= raw recursive_comments(comment, temp, content) unless comment.comments.empty? %>
  <% end %>
</div>


<script>
$(".delCom").click(function() {
    alert('dfdf');
    $(".delCom").parent(".comment").hide().html('Deleted UNDO?').fadeIn("fast");
   
});
</script>

app/views/comments/_form.html.erb
<h1 id='comment-header'>New Comment</h1>

<%= form_for [@commentable, @comment]  do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h2>Please correct the following errors.</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :commentable_id, value: @commentable.id%>
    <%= f.hidden_field :commentable_type, value: "Video"%>
    <%= f.text_area :content, rows: 8 %>
  </div>
  <div class="actions">
    <%if user_signed_in?%>
    <%= f.submit 'Comment'%>
    <%else%>
    <div class="btn" id="fake_button"> Comment </div>
    <div id="comment_sign_in" style="display:none">
      <%=link_to "You must be signed in to comment", new_user_session_path%>
    <div>
    <%end%>
  </div>
<% end %>

<script>
$('#fake_button').click(function(){
  $(this).hide();
  $('#comment_sign_in').show();
});
</script>

app/views/comments/comment.html.erb
<div id="comments" style="margin-left: <%=temp%>px;" >
      <div class="comment">
        <div id="comTitle" >
          <span id="comUser">
            <% if user_signed_in? %>
            <%=link_to comment.user.username, user_path(comment.user_id)%>
            <% else %>
                 <%=link_to comment.user.username, new_user_session_path, :onclick => "alert('You need to sign in or sign up before continuing.')" %> 
            <% end %>
            
          </span>
          <span class='text-right created-at'><%= comment.created_at.strftime('%B/%e/%Y %H:%M:%S') %></span>
          <div id="comImg" >
            <% image = get_image comment.user%>
            <%= image_tag image, :style=> "background:#555;max-height:50px;float:left;"%>
          </div>
        </div>
        <p><%= simple_format comment.content %></p>
        <div class='comment-footer row-fluid'>
          <p>
            <%= (link_to 'reply', '#', class: 'reply', data_value: comment.id, data_user_info: "New comment to #{comment.user.username} comment, created at #{comment.created_at.strftime('%B/%e/%Y %H:%M:%S')}" if user_signed_in?) %>
            <% if user_signed_in? && comment.was_not_liked_by?(current_user) %>
              <%= link_to '#', class: 'comment-like like', data_user_id: current_user.id, data_like: true, data_id: comment.id, data_send_to: comment_likes_path do %> 
                <%= image_tag 'like.png', class: 'like-finger' %>
              <% end %>
            <% else %>
              <% if user_signed_in? %>
                <% class_l =  comment.was_liked_positive_by?(current_user.id) ? 'this_value' : "" %>
              <% end %>
              <%= image_tag 'like.png', class: 'has-ben-liked '+ class_l ||= ""%>
            <% end %>
            <span class='like-count'> <%= comment.comment_likes.where(like_or_not: true).count %> </span>
            <%  if user_signed_in? && comment.was_not_liked_by?(current_user) %>
              <%= link_to '#', class: 'comment-like dethlike', data_user_id: current_user.id, data_like: false, data_id: comment.id, data_send_to: comment_likes_path do %> 
                <%= image_tag 'd_like.png', class: 'like-finger' %>
              <% end %>
            <% else %>
              <% if user_signed_in? %>
                <% class_l =  comment.was_liked_positive_by?(current_user.id) ? "" : 'this_value' %>
              <% end %>
              <%= image_tag 'd_like.png', class: 'has-ben-liked '+ class_l ||= "" %>
            <% end %>
            <span class='dethlike-count'> <%= comment.comment_likes.where(like_or_not: false).count %> </span>
          </p>
        </div>     
      </div>
    </div>

app/views/comments/create.js.erb
$(".delCom").parent(".comment").hide().html('Deleted UNDO?').fadeIn("fast");

app/views/comments/new.html.erb
<h3>New Comment</h3>

<%= form_for [@commentable, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h2>Please correct the following errors.</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, rows: 8 %>
  </div>
  <div class="actions">
    <%= f.submit, :remote => true %>
  </div>
  <script>
$(".actions").click(function() {
  
     $parent().hide().html('Deleted UNDO?').fadeIn("fast");
   
});
</script>
<% end %>

app/views/comments/new.js.erb
$('#new_comment').hide().after('<%= j render("form") %>');

app/views/comments/show.html.erb
<%= render :partial => 'comments/comments', :object => Comment.find(params[:id]) %>