config/routes.rb
Mmagap::Application.routes.draw do
  
  
  root :to => 'videos#index'
  
  
  #devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) 
  devise_for :admin_users, ActiveAdmin::Devise.config


  resources :student_teacher_profiles
  resources :comments
  resources :comment_likes
  resources :likes


  #resources :videos  
  
  
  #following system
  resources :relationships, only: [:create, :destroy]
 
  post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"
  get 'tags/:tag', to: 'videos#tag_page', as: :tag
  
 
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  devise_for :users, :controllers => {:registrations => "registrations"}
    
  #devise_for :users
  match 'users/:id' => 'users#show'

  devise_scope :user do
    get 'register' , :to => 'devise/registrations#new', as: :register
    get 'mydashboard', :to => 'users#dashboard', as: :mydashboard
    get 'user/following/:id', to: 'users#following', as: :following
    get 'user/followers/:id', to: 'users#followers', as: :followers
  end
  

  match '/home' => 'videos#index', :as => 'home'

  
  resources :videos do
    collection do
      #get 'lesson' => 'videos#lesson', :as => 'lesson'
      #post 'lesson_create' => 'videos#lesson_create', :as => 'lesson_create'
      get '/lesson' => 'videos#lesson', :as => 'lesson'
      post '/lesson' => 'videos#lesson_create', :as => 'lesson_create'
    end
  end
  
  get '/lesson' => 'videos#lesson', :as => 'lesson'
  post '/lesson' => 'videos#lesson_create', :as => 'lesson_create'
  
  get '/show_lesson_video/:id' => 'videos#show_lesson_video', :as => 'show_lesson_video'
  get '/purches_lesson_video/:id' => 'videos#purches_lesson_video', :as => 'purches_lesson_video'
  
  #get '/lesson_checkouts' => 'lesson_checkouts#index'
  
  resources :lesson_checkouts
  #get '/lesson_checkout/new/:video_id' => 'lesson_checkouts#new', :as => 'lesson_pay_new'
  #post '/lesson_checkout/new/:video_id' => 'lesson_checkouts#create', :as => 'lesson_pay_create'
  
  get '/lesson_checkout/new/' => 'lesson_checkouts#new', :as => 'lesson_pay_new'
  post '/lesson_checkout/new/' => 'lesson_checkouts#create', :as => 'lesson_pay_create'
  
  get '/paypal_pro/:id' => 'lesson_checkouts#paypal_pro', :as => 'paypal_pro'
  post '/paypal_pro/:id' => 'lesson_checkouts#paypal_do_direct', :as => 'paypal_do_direct'
  
  
  get '/paypal_success/:id' => 'lesson_checkouts#paypal_success', :as => 'paypal_success'
  get '/paypal_failure/:id' => 'lesson_checkouts#paypal_failure', :as => 'paypal_failure'
  get '/paypal_ipn/:id' => 'lesson_checkouts#paypal_ipn', :as => 'paypal_ipn'
  
  #get '/paypal_do_direct/:id' => 'lesson_checkouts#paypal_do_direct', :as => 'paypal_do_direct'
  #get '/paypal_do_direct/:id' => 'lesson_checkouts#paypal_do_direct_new', :as => 'paypal_do_direct_new'
 
  
  
  
  match '/tags' => 'videos#tag_page', :as => 'tags'
  resources :videos do
    member do
      get 'inappropriate'
    end 
          resources :comments
          member { post :vote }
    end


  resources :users
  resources :plans
  resources :subscriptions
  
  resources :inquiries, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end

  #get "paypal/new/:plan_id", to: "subscriptions#new", as: :new
  #get "paypal/checkout", to: "subscriptions#paypal_checkout", as: :paypal_checkout
  
  match '/paypal/checkout'=>'subscriptions#paypal_checkout'
  get '/paypal/checkout'=>'subscriptions#paypal_checkout'
  
  #get "paypal/checkout", to: "subscriptions#paypal_checkout"
 
 

  resources :requests
  resources :homes

  match "/404", :to => "videos#index"

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  match '/new_within_follow' => 'conversations#new_within_follow', via: :get
  match '/start' => 'conversations#start', :via => :get
  match '/find_user' => 'users#find_user', :via => :get

  resources :messages
    match '/profile' => 'users#profile', :via => :get
    match '/userspage' => 'static#userspage', :via => :get
    match '/help' => 'static#help', :via => :get
    match '/termsofuse' => 'static#termsofuse', :via => :get
    match '/aboutus' => 'static#aboutus', :via => :get
    match '/contactus' => 'static#contactus', :via => :get
  
  match 'cms_pages/show/:id' => 'cms_pages#show'
  
  
    
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  helper_method :mailbox, :conversation

  def create
    recipient_emails = conversation_params(:recipients).split(',')
    recipients = User.where(email: recipient_emails).all

    conversation = current_user.
      send_message(recipients, *conversation_params(:body, :subject)).conversation
    if user_signed_in?
      render :index, locals: {user: current_user}
    else
      redirect_to root_path
    end
  end

  def new_within_follow
  end

  def start
  end

  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    redirect_to conversation
  end


  def trash
    conversation.move_to_trash(current_user)
    render :index, locals: {user: current_user}
  end

  def untrash
    conversation.destroy
    render :index, locals: {user: current_user}
  end

  private
  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
      when 0 then self
      when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end
end

app/views/conversations/_conversation.html.erb
<div class='row-fluid'>
  <%=content_tag_for(:li, conversation) do |conversation|%>
    <div class='span12 conversation-container row-fluid' style='margin-left:0;'>
      <div class='span3 user-name'>
        <div>
          <% user = conversation.receipts.first.receiver == current_user ? conversation.messages.first.sender  : conversation.receipts.first.receiver %>
          <%= link_to user.username, user %>
        </div>
        <div>
          <% image = get_image user %>
          <%= image_tag image, style: "background:#555;max-height:80px;float:left;" %>
        </div>
      </div>
      <div class='conversation-message span8'>
        <div class='page-header'>
          <h1 class='conversation-subject'>
            <%= link_to "Go to #{conversation.subject} conversation", conversation%> 
            <span class='pull-right time'><%=l conversation.updated_at.in_time_zone("America/New_York"), :format => :long %></span>
          </h1> 
        </div>
        <%=truncate(conversation.messages.last.body, length: 210)%>
      </div>
      <%if conversation.is_completely_trashed?(current_user)%>
        <%= link_to image_tag('error.png', size: '15x15'), [:untrash, conversation], method: :post, id: "delete-conversation" %>
      <%else%>
        <%= link_to image_tag('error.png', size: '15x15'), [:trash, conversation], method: :post, id: "delete-conversation" %>
      <%end%>
    </div>
  <%end%>
</div>

          

app/views/conversations/_form.html.erb
<div id="new-conversation-form">
  <% unless params[:recipients] %>
    <%= form_tag find_user_path, method: 'get', id: 'find-user-by-email' do %>
      <div class="input string required email-finder">
        <label class="string required control-label" for="email">
          <abbr title="required">*</abbr>
          Find user by mail
        </label>
        <%= text_field_tag :search, params[:search] %>
        <div id="responce">Not found</div>
      </div>
    <% end %>
  <% end %>
  <%= simple_form_for :conversation, url: :conversations, html: {id: 'main-conversation-form'} do |f| %>
    <% if !params[:recipients] %>
      <%= f.input :recipients, as: :hidden, required: true %>
    <% else %>
      <%= f.input :recipients, as: :hidden, required: true, input_html: { value: params[:recipients] } %>
    <% end %>
    <%= f.input :subject %>
    <%= f.input :body, as: :text %>
    <%= f.button :submit, :class=> 'btn pull-right', :value => "Send Message" %>
  <% end %>
  <div class="clear"></div>
</div>

app/views/conversations/_form1.html.erb
<%= simple_form_for :conversation, url: :conversations do |f| %>
  <%= f.input :recipients, :as => :hidden ,:input_html => { :value => params[:recipients] } %>
  <%= f.input :subject, :input_html => {:value => params[:deal_name]}, :class=>"span12"  %>
  <%= f.input :body, as: :text, :input_html => { :cols => 50, :rows => 3 } %>
  <div class="form-actions">
    <%= f.button :submit,  :class=> 'btn btn-large btn-success', :value => "Send Message" %>
  </div>
<% end %>

app/views/conversations/_form2.html.erb
<%= simple_form_for :conversation, url: :conversations do |f| %>
  <h1>
    <%= link_to params[:message_username].capitalize, request.referer %>
  </h1>
  <%= f.input :recipients, :as => :hidden ,:input_html => { :value => params[:recipients] } %>
  <%= f.input :subject %>
  <%= f.input :body %>
  <div class="form-actions">
    <%= f.button :submit, :class=> 'btn btn-large btn-success', :value => "Send Message" %>
  </div>
<% end %>

app/views/conversations/index.html.erb
<% if defined? user %>
  <% mailbox ||= user.mailbox  %>
<% end %>
<div class="container container-home">
  <div class="row-fluid">
    <div class="span12 well">
      <h1>Conversations</h1>
      <h2>Inbox</h2>
      <ul>
        <%= render mailbox.inbox %>
      </ul>
      <h2>Sentbox</h2>
      <ul>
        <%= render mailbox.sentbox %>
      </ul>
      <h2>Trash</h2>
      <ul>
        <%= render mailbox.trash %>
      </ul>
      <br/>
      <br/>
      <% if user_signed_in?  %>
        <%= link_to 'Start Conversation', start_path(message_username: user.name), class: 'btn', id: 'start-conversation', remote: true %>
      <% end %>
    </div>
  </div>
</div>

app/views/conversations/new.html.erb
<h1>
  <%= "To: #{params[:message_username]}"  %>
</h1>
<%= render 'form1' %>

app/views/conversations/new.js.erb
$('#user_link').hide().after('<%= j render("form") %>');

app/views/conversations/new_within_follow.js.erb
$('.removable-c-link').hide().after('<%= j render("form") %>');

app/views/conversations/show.html.erb
<h1><%= conversation.subject%> </h1>
  <%= content_tag_for(:li, conversation.receipts_for(current_user)) do |receipt|%>
    <div class='span12 conversation-container row-fluid' style='margin-left:0;'>
      <div class='span3 user-name'>
        <div>
          <% user = receipt.message.sender %>
          <%= link_to user.username, user %>
        </div>
        <div>
          <% image = get_image user %>
          <%= image_tag image, style: "background:#555;max-height:80px;float:left;" %>
        </div>
      </div>
      <div class='conversation-message span8'>
        <div class='page-header'>
          <h1 class='conversation-subject'>
            <p class='pull-right time'><%=l receipt.message.created_at.in_time_zone("America/New_York"), :format => :long %></p>
            <div class='clear'></div>
          </h1> 
        </div>
        <%=truncate(receipt.message.body, length: 210)%>
      </div>
    </div>
  <%end%>
<%= render 'messages/form', conversation: conversation%>

app/views/conversations/start.js.erb
$('#start-conversation').hide().after('<%= j render("form") %>');