config/routes.rb
Mmagap::Application.routes.draw do
  
  
  root :to => 'videos#index'
  
  
  #devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) 
  devise_for :admin_users, ActiveAdmin::Devise.config


  resources :student_teacher_profiles
  resources :comments
  resources :comment_likes
  resources :likes


  #resources :videos  
  
  
  #following system
  resources :relationships, only: [:create, :destroy]
 
  post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"
  get 'tags/:tag', to: 'videos#tag_page', as: :tag
  
 
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  devise_for :users, :controllers => {:registrations => "registrations"}
    
  #devise_for :users
  match 'users/:id' => 'users#show'

  devise_scope :user do
    get 'register' , :to => 'devise/registrations#new', as: :register
    get 'mydashboard', :to => 'users#dashboard', as: :mydashboard
    get 'user/following/:id', to: 'users#following', as: :following
    get 'user/followers/:id', to: 'users#followers', as: :followers
  end
  

  match '/home' => 'videos#index', :as => 'home'

  
  resources :videos do
    collection do
      #get 'lesson' => 'videos#lesson', :as => 'lesson'
      #post 'lesson_create' => 'videos#lesson_create', :as => 'lesson_create'
      get '/lesson' => 'videos#lesson', :as => 'lesson'
      post '/lesson' => 'videos#lesson_create', :as => 'lesson_create'
    end
  end
  
  get '/lesson' => 'videos#lesson', :as => 'lesson'
  post '/lesson' => 'videos#lesson_create', :as => 'lesson_create'
  
  get '/show_lesson_video/:id' => 'videos#show_lesson_video', :as => 'show_lesson_video'
  get '/purches_lesson_video/:id' => 'videos#purches_lesson_video', :as => 'purches_lesson_video'
  
  #get '/lesson_checkouts' => 'lesson_checkouts#index'
  
  resources :lesson_checkouts
  #get '/lesson_checkout/new/:video_id' => 'lesson_checkouts#new', :as => 'lesson_pay_new'
  #post '/lesson_checkout/new/:video_id' => 'lesson_checkouts#create', :as => 'lesson_pay_create'
  
  get '/lesson_checkout/new/' => 'lesson_checkouts#new', :as => 'lesson_pay_new'
  post '/lesson_checkout/new/' => 'lesson_checkouts#create', :as => 'lesson_pay_create'
  
  get '/paypal_pro/:id' => 'lesson_checkouts#paypal_pro', :as => 'paypal_pro'
  post '/paypal_pro/:id' => 'lesson_checkouts#paypal_do_direct', :as => 'paypal_do_direct'
  
  
  get '/paypal_success/:id' => 'lesson_checkouts#paypal_success', :as => 'paypal_success'
  get '/paypal_failure/:id' => 'lesson_checkouts#paypal_failure', :as => 'paypal_failure'
  get '/paypal_ipn/:id' => 'lesson_checkouts#paypal_ipn', :as => 'paypal_ipn'
  
  #get '/paypal_do_direct/:id' => 'lesson_checkouts#paypal_do_direct', :as => 'paypal_do_direct'
  #get '/paypal_do_direct/:id' => 'lesson_checkouts#paypal_do_direct_new', :as => 'paypal_do_direct_new'
 
  
  
  
  match '/tags' => 'videos#tag_page', :as => 'tags'
  resources :videos do
    member do
      get 'inappropriate'
    end 
          resources :comments
          member { post :vote }
    end


  resources :users
  resources :plans
  resources :subscriptions
  
  resources :inquiries, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end

  #get "paypal/new/:plan_id", to: "subscriptions#new", as: :new
  #get "paypal/checkout", to: "subscriptions#paypal_checkout", as: :paypal_checkout
  
  match '/paypal/checkout'=>'subscriptions#paypal_checkout'
  get '/paypal/checkout'=>'subscriptions#paypal_checkout'
  
  #get "paypal/checkout", to: "subscriptions#paypal_checkout"
 
 

  resources :requests
  resources :homes

  match "/404", :to => "videos#index"

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  match '/new_within_follow' => 'conversations#new_within_follow', via: :get
  match '/start' => 'conversations#start', :via => :get
  match '/find_user' => 'users#find_user', :via => :get

  resources :messages
    match '/profile' => 'users#profile', :via => :get
    match '/userspage' => 'static#userspage', :via => :get
    match '/help' => 'static#help', :via => :get
    match '/termsofuse' => 'static#termsofuse', :via => :get
    match '/aboutus' => 'static#aboutus', :via => :get
    match '/contactus' => 'static#contactus', :via => :get
  
  match 'cms_pages/show/:id' => 'cms_pages#show'
  
  
    
end

app/models/video.rb
class Video < ActiveRecord::Base
  
  
  include Paperclip::Glue
  
  attr_accessible :title, :video_link,:file, :category, :tag_list, :views, :user_id, :innappropriate,
  :description, :lesson_upload, :price, :is_active, :tag_ids
  
  has_attached_file :lesson_upload

  
  #validates_presence_of :panda_video_id
  validates_presence_of :title
  validates :description, presence: true, length: { in: 1..200 }
  
  validates :price, :format => { :with => /^\d+??(?:\.\d{0,2})?$/ }, :numericality => { :less_than => 9999999999}
  
  #validates_attachment_presence :lesson_upload
  #validates_attachment_size :lesson_upload, :less_than => 50.megabytes
  #validates_attachment_content_type :lesson_upload, :content_type => ['video/mp4', 'video/avi','video/mpeg', 'video/flv']
  #validates_attachment_content_type :lesson_upload, :content_type => ['video/mp4', 'video/avi','video/mpeg', 'video/flv']
  #validates_attachment_content_type :lesson_upload,
                                    #:content_type => ['video/mp4'],
                                    #:message => "Sorry, right now we only support MP4 video.",
                                    #:if => :is_type_of_video?


  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  has_many :plan
  has_many :lesson_checkout
  acts_as_taggable
  is_impressionable
  make_flaggable :inappropriate

  before_create :make_up_to_date

  mount_uploader :attachment, VideoUploader
 
 

  def set_success(format, opts)
    self.success = true
  end

  def processed!
    update_attribute(:processed, true)
  end


  has_reputation :votes, source: :user, aggregated_by: :sum

  scope :needs_feedback, where(:category=> "Needs-Feedback")
  scope :how_to, where(:category=> "How-To")
  scope :demo, where(:category=> "Demo")
  scope :lesson, where(:category=> "Lesson")

  scope :last_x_days, lambda { |x| where("created_at >= :date", :date => (DateTime.now - x.days)) }

  CATEGORIES = %w[Needs-Feedback How-To Demo Lesson]

  def was_vouted_by? user
    self.evaluations.find_by_source_id(user.id)
  end

  def how_was_vouted_by user
    value = self.evaluations.find_by_source_id(user.id)
    if value
      return "positive" if value.value > 0
      return "negative" if value.value < 0
    end
  end

  def category_symbols
    categories.map do |category|
      category.name.underscore.to_sym
    end
  end

  def been_liked_by? user
    res = self.likes.map { |like| like.user_id == user.id ? true : false } 
    res = res[0] if res.kind_of?(Array)
  end

  def have_same_tags_as? obj
    temp = false
    self.tags.each do |outer_tag|
      obj.tags.each do |inner_tag|
        temp = true if outer_tag.name == inner_tag.name
        break if temp
      end
      break if temp
    end
    temp
  end
  
  protected
    def is_type_of_video?
        lesson_upload.content_type =~ %r(video)
    end
    
  
  private
    def make_up_to_date
      self.tags.each {|tag| tag.updated_at = Time.now}
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate_user!, :except => [:tag_page, :index, :show]
  
  #layout :resolve_layout
  
  # GET /videos
  # GET /videos.json
  impressionist :actions=>[:show]
  def vote
    value = params[:type] == "up" ? 1 : -1
    @video = Video.find(params[:id])
    @video.add_or_update_evaluation(:votes, value, current_user)

    respond_to do |format|
      format.js 
    end
  end 

  def inappropriate
    @video = Video.find(params[:id])
    current_user.flag(@video, :inappropriate) 
    redirect_to @video, notice: "Video HAS been FLAGGED!!" 
  end

  def tag_page
    @videos = Video.tagged_with(params[:tag]).page(params[:page]).per(10)
    respond_to do |format|
      format.html # index.html.erb
      format.js { render "renew_results"}
    end
  end


  def index
    
    process_search_params
  
    respond_to do |format|
      format.html # index.html.erb
      format.js { render "renew_results" }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show


    @video = Video.find(params[:id])
    
    @vid = params[:id]
    #@video = Video.where(:id=>@vid, :is_active=>'1').take
    #@video = Video.where("id = ? AND is_active = ?", @vid, 1)
 
      @video_id = (/([\w-]{11})/.match(@video.video_link)).to_s
      @embed_code =  %Q{<iframe title="YouTube video player" style=" margin-top: 24px;" width="640" height="390" src="http://www.youtube.com/embed/#{ @video_id}" frameborder="0" allowfullscreen></iframe>}
      
   
    @commentable = @video
    @comments = @commentable.comments
    @comment = Comment.new
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end
 
  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  
  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    
    #@video = params
    params[:video]['price'] = '0.00';
    params[:video]['is_active'] = '1';
    #params[:video]['lesson_upload'] = 'no_image';
    #params[:video]['lesson_upload_file_name'] = 'no_image';
    #params[:video]['lesson_upload_content_type'] = 'no_image';
    #params[:video]['lesson_upload_file_size'] = '0';
 
    
        
    @video = current_user.videos.build(params[:video])
    respond_to do |format|
      if @video.save
        #@video.convert
        VideoMailer.video_confirmation(@video).deliver
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
      else
        format.html { render action: "new" }
        format.js
      end
    end
  end


  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
  
  
  
  # GET /videos/lesson
  # GET /videos/lesson.json
  def lesson
    @video = Video.new
    @tags = Tag.find(:all)
    
    @mytag = []
    @tags.each do |tag|
      @mytag.push(tag.name)
    end

    respond_to do |format|
      format.html # lesson.html.erb
      format.json { render json: @video }
    end
  end
  
   # POST /videos
  # POST /videos.json
  def lesson_create
    
    #@video = params
    params[:video]['category'] = 'Lesson';
    params[:video]['is_active'] = '0';
     

    @video = current_user.videos.build(params[:video])
    if @video.save
     
      @title = params[:video]['title']
      @price = @subscriptions_price
      @rtime = @subscriptions_time
      @video_id = @video.id
      
      @lastinsertid = Plan.create(:name => @title, :price => @price, :time => @rtime, :video_id => @video_id)
     
      #redirect_to(new_subscription_path,1)
      redirect_to :controller => 'subscriptions', :action => 'new', :plan_id =>  @lastinsertid.id
    else
      respond_to do |format|
        format.html { render action: "lesson" }
        format.js
      end  
    end
  end
  
  def show_lesson_video
    
    @vid = params[:id]
    @userid = current_user.id
    @video1 = Video.find(@vid) 
    
    
    if (@video1.user_id != @userid)
      
      @pyment_status = LessonCheckout.where("user_id = ? AND video_id = ?", @userid, @vid)
      
     
      if  !@pyment_status.empty?
         
          @pyment_status.each do |p_stats|
           
            if (p_stats['payment_status'] !='' && p_stats['payment_status']=='success')
                @video = @video1
                @commentable = @video
                @comments = @commentable.comments
                @comment = Comment.new
                respond_to do |format|
                  format.html # show.html.erb
                  format.json { render json: @video }    
                end 
            else
              redirect_to "/purches_lesson_video/#{@vid}"
            end   
            
          end  
          
      else
          redirect_to "/purches_lesson_video/#{@vid}"
      end
    
    else
      @video = @video1
      @commentable = @video
      @comments = @commentable.comments
      @comment = Comment.new
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @video }    
      end 
    end
  end
    
    
  def purches_lesson_video
    
    @vid = params[:id]
    @video = Video.find(@vid)
    @lesson_checkout = LessonCheckout.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end
  
  def my_checkout
    
    
    @data = params
    
    #@vid = User.find(params[:id])
    #@video = Video.find(@vid)
    
    #respond_to do |format|
      #format.html # show.html.erb
      #format.json { render json: @video }
    #end
  end
  
  def my_checkout_create
    
    @vid = params[:id]
    @video = Video.find(@vid)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end   
  
  private

    def process_search_params

      if params[:q].present? && params[:q][:created_at_lteq].present? && params[:q][:created_at_lteq] != "active"
         time_days = params[:q][:created_at_lteq].to_i
      else
          time_days = 10000
      end

      if params[:q]
        params[:tag] ||= params[:q][:tag] unless params[:q][:tag].nil? || params[:q][:tag].empty?
      end

      if params[:tag]
        @search = Video.search(params[:q]).where('is_active =?',true)
        @videos = @search.result(:distinct => true).tagged_with(params[:tag]).where('is_active =?',true).order("created_at desc").page(params[:page]).per(10)
      
      else
        @search=Video.search(params[:q])
        @videos= @search.result(:distinct => true).last_x_days(time_days).where('is_active =?',true).order("created_at desc").page(params[:page]).per(10)
        if params[:q]
          unless params[:q][:created_at_lteq]
            @tagged_videos = Video.tagged_with(params[:q][:title_cont])
            @tagged_videos.each { |tv| @videos << tv unless @videos.include? tv }
          end
        end
      end
      
   
    end
    
    
    #private
    #def resolve_layout
      #case action_name
      #when "simple"
       # "video"
      #when "advanced"
      #  "video"
      #else
      #  "application"
      #end
    #end


end

app/helpers/videos_helper.rb
module VideosHelper

  def recursive_comments comment, temp, content
    temp += 10
    comment.comments.each do |comment|
      content += render(:template =>"comments/comment", :layout => nil , :locals => { comment: comment, temp: temp }).to_s
      content += recursive_comments(comment, temp, "") unless comment.comments.empty?
    end #comment.each do |comment|
    return content
  end

end

app/views/videos/_form_lesson.html.erb
<%#= form_for @lesson_new_path, :url => {:controller=>'videos', :action => 'lesson_new'} do |f| %>
<%= form_for @video, :url=>lesson_create_path do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :category, :value=>'Lesson' %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
    <%#= show_field_error(@video, :title) %>
  </div>
  <div class="line">
      <label for="tags">Tags</label>
      <ul id="mytags3"></ul>
    </div>
  <div class="field">

  <%= f.label :tag_list, "Tags (separated by commas)" %><br /> <!-- I DON'T KNOW IF WE NEED THIS -->
  <div style="display:none;"><%= f.text_field :tag_list, :id=>'video_tag_list3' %></div>
  </div>
  
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
    <%#= show_field_error(@video, :price) %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, as: :hidden%>
    <%#= show_field_error(@video, :description) %>
  </div>
  
  
  <div class="field">
 	<%= f.file_field(:lesson_upload)  %>
        <%#= f.hidden_field(:lesson_upload) %>
        <%#= show_field_error(@video, :lesson_upload) %>
  </div>
  
  <div class="actions">
    <%= f.submit 'Upload'%>
  </div>
<% end %>

app/views/videos/_tag.html.erb
<tr>
    <td><div id="click_tag"> <%= link_to tag.name, videos_path(tag: tag.name), class: "#{css_class} tag-link"%></div></td>  
    <td><%= tag.count%> </td>
</tr>

app/views/videos/confirm.html.erb
<div id="content">
<h1>Paypal Recurring Payment Mathod</h1>

<%= render 'form_paypal_recurring' %>


 <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
<script>

$(document).ready(function(){

  
    $("#mytags3").tagit({
      availableTags: ["mma", "karate", "karatedo", "taekvando", "javascript", "asp", "ruby", "python", "c", "scala", "groovy", "haskell", "perl"]
    });
   
    
 

}); 


</script>

<h2>Upload your Video</h2>
<div id="video_attachment"></div>
<%= link_to "Video Listing", videos_path %>
<%= link_to 'Back', videos_path %>
</div>

app/views/videos/create.js.erb
<%- if @video.errors.any? %>
  console.log('Error');
  $('#new_video').html('<%= escape_javascript(render('videos/form')) %>');
<%- else %>
  console.log('Created');
  location.reload();
<%- end %>

app/views/videos/create__.erb
<%= debug params %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/new.html.erb
<div id="content">
<h1>New video</h1>

<%= render 'form' %>

<h2>Upload your Video</h2>
<div id="video_attachment"></div>
<%= link_to "Video Listing", videos_path %>
 
 
<script type="text/javascript">
  $(function() {
    <% session_key = Rails.application.config.session_options[:key] %>
    var uploadify_script_data = {};
    var csrf_token = $('meta[name=csrf-token]').attr('content');
    var csrf_param = $('meta[name=csrf-param]').attr('content');
 
    uploadify_script_data[csrf_param] = encodeURI(encodeURIComponent(csrf_token));
    uploadify_script_data['<%= session_key %>'] = '<%= cookies[session_key] %>';
 
    $('#video_attachment').uploadify({
      uploader  : '<%= asset_path("assets/javascripts/uploadify.swf") %>',
      script    : '<%= videos_path %>',
      wmode     : 'transparent',
      cancelImg : '<%= asset_path("assets/javascripts/cancel.png") %>',
      fileDataName    : 'attachment',
      scriptData : uploadify_script_data,
      auto      : true,
      buttonText : 'Browse',
      onAllComplete : function(event, data){
        alert("Success!  Please be patient while the video processes.");
      },
      onError: function(event, ID, fileObj, errorObj){
        alert("There was an error with the file you tried uploading.\n Please verify that it is the correct type.")
      }
    });
  });
</script>
<%= link_to 'Back', videos_path %>
</div>

app/views/videos/paypal_recurring.html.erb
<div id="content">
<h1>Paypal Recurring Payment Mathod</h1>

<%= render 'form_paypal_recurring' %>


 <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
<script>

$(document).ready(function(){

  
    $("#mytags3").tagit({
      availableTags: ["mma", "karate", "karatedo", "taekvando", "javascript", "asp", "ruby", "python", "c", "scala", "groovy", "haskell", "perl"]
    });
   
    
 

}); 


</script>

<h2>Upload your Video</h2>
<div id="video_attachment"></div>
<%= link_to "Video Listing", videos_path %>
<%= link_to 'Back', videos_path %>
</div>

app/views/videos/postprocess.html.erb
<%= debug @video_params %>

app/views/videos/show_lesson_video.html.erb
<%#= debug @@pyment_status %>
<div id="mainVideoWrap" style="">
<div id="mainVideoCont" >
  <div id="mainVideoContText"> 
    <h2>Related Videos</h2>
    <div id="thumb-stats 1" style="width:240px" >
      <% Video.where(:category=> @video.category).each do |video|%>
	<% if video.have_same_tags_as? @video %>
	  <div id="liked-desc" style="float:right; width:110px;">
	    <%=link_to video.title, video%> 
	  </div>
	  <div class="video-user-small" url="<%=video.video_link%>" style="margin-bottom:5px;width:110px;" >
	    <%=link_to "", video%> 
	  </div>
	  <div class='clear'></div>
	<% end %>
      <%end%>
    </div> 
  </div>
</div>

<div id="header-desc" id="lft" style="width:69%;">
<h3><%= @video.title %></h3>
<div id="rgt">
  <div class="votera" style="float:right;">
    <% if user_signed_in? %>
      <% unless @video.was_vouted_by?(current_user) %>
	<%= link_to image_tag('like.png', class: 'vide-like', :style=> "text-align:left; width:20px").html_safe, vote_video_path(@video,type: "up"), method: :post, remote: true , :class => "voter voter-up" %>
	<%= link_to  image_tag('d_like.png', class: 'vide-like', :style=> 'text-align:right; width:20px'), vote_video_path(@video,type: "down"), method: :post, remote: true , :class => "voter" %>
      <% end %>
      <% if @video.how_was_vouted_by current_user %>
	<% l_img = ((@video.how_was_vouted_by (current_user)) == "positive") ? "like.png" : 'd_like.png' %>
	<%= image_tag l_img, class: 'how-was-liked',:style=> 'text-align:right; width:20px' %>
      <% end %>
    <% end %>
    <span id='vote-value' class='votes btn '><%= pluralize @video.reputation_for(:votes).to_i, "vote" %></span>
  </div>
  <div id="rgt" class="btn btn-info"><%= link_to "Request Training", @video.user, id: "new_link", :style=>"color:black;" %></div>
  <div id="rgt" class="btn btn-warning"><%=link_to "Flag", inappropriate_video_path(@video), :style=> "color:black;"%></div>
  <% if user_signed_in? %>
    <% if @video.been_liked_by? current_user%>
      <%= link_to current_user.this_video_like(@video.id), method: :delete, id: 'delete_like' do %>
	<div id='rgt' class='btn btn-info'>
	  <%= image_tag '200ok.png', size: '20x20'%> 
	</div>
      <% end %> 
    <% else %>
      <a href='#' id='new_like_button'>
	<div id='rgt' class='btn btn-info'>
	  Like
	  <%= simple_form_for(@like = Like.new) do |f| %>
	    <%= f.input :user_id, as: :hidden, input_html: {value: current_user.id} %>
	    <%= f.input :video_id, as: :hidden, input_html: {value: @video.id} %>
	  <% end %>
	</div>
      </a>
    <% end %>
  <% end %>
</div>

	

  </div>
	     <div id="vidProfile">
	      <% image = get_image @video.user%>
	      <%= image_tag image, :style=> "background:#555;max-height:50px;float:left;"%>
	    </div>
	    <div id="vidPoints lft">
		<li>Activity Points:<b> 2</b></li>
		<li>Pro Points:<b> 2</b></li>
	    </div>
       
	<!--#lesson video-->
	<!-- the player -->
	<%#= @video.lesson_upload %>
	
	<!--<script src="//releases.flowplayer.org/5.4.6/flowplayer.min.js"></script>-->
	<%= javascript_include_tag "flowplayer/flowplayer.js"%>
	<div class="flowplayer">
	   <video>
	      <source type="video/mp4" src="<%= @video.lesson_upload %>">
	   </video>
	</div>
		
	
      <div style="height:20px;">&nbsp</div>
      <div id='vid-info-s' class='row-fluid' style="background:#ccc; width:640px; height:auto;">
	<div class='span6' id='video-description-span'>
	  <div class='page-header'>
	    <h5>Video Description</h5>
	  </div>
	  <% if @video.description %>
	    <p><%= @video.description %></p>
	  <% else %>
	    <p class='a-little-hint'>No description added...</p>
	  <% end %>
	</div>
	<div class='span6' id="rgt video-attributes-span"> 
	  <div id="statbox" style="width:155px;float:right;">   
	    <ul id="stats-top"> 
	      <li class="views" style="float:left;width:40px; list-style-type:none;"><%=@video.impressionist_count%></li>
	      <li class="views" style="float:left;width:65px; list-style-type:none;"><%=@video.comments.count%></li>
	      <li class="views" style="float:left;width:40px;list-style-type:none;"><%=@video.reputation_for(:votes).to_i%></li>
	    </ul>
	    <ul id="stats-bot"> 
	      <li class="views" style="float:left;width:40px; list-style-type:none;">VIEWS</li>
	      <li class="views" style="float:left;width:65px; list-style-type:none;">COMMENTS</li>
	      <li class="views" style="float:left;width:40px;list-style-type:none;">VOTES</li>
	    </ul>
	  </div>
	  <p id="lft"> 
	    <span id="rgt">
	      <%@video.tags.limit(4).each do |tag|%>
		<%= link_to tag, videos_path(tag: tag.name), :id=>"tag-"%>
	      <%end%>
	    <span>
	  </p>
	  <div class='clear'></div>
	
	  <div class="social">
	    <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
	    <a class="addthis_button_preferred_1"></a>
	    <a class="addthis_button_preferred_2"></a>
	    <a class="addthis_button_preferred_3"></a>
	    <a class="addthis_button_compact"></a>
	  </div>
	  <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
	  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-500880a75781d23d"></script>
	</div>
      </div> <!--end <div style="background:#ccc; width:640px; height:100px;">-->
      <% if is_signed_in_this? @video.user %>
	<div id='show-vid-controle-btns'>
	  <div class='btn-group'>
	    <%= link_to 'Edit', edit_video_path(@video), class: 'btn' %>
	    <%= link_to 'Delete', @video, method: :delete, :confirm => 'Are you sure?', class: 'btn btn-danger' %>
	  </div>      
	</div>
      <% end %>
    </div>
  <br>  
</div>